name: Qodana
on: 
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - staging
      
jobs:
  qodana:
    runs-on: ubntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-actions@v2022.1.1  
